name: github_Angelo.github.io
url:  https://liuliminga.github.io/github_Angelo.github.io/
description: Insert tagline here

permalink: /themes/:title/

plugins: [jekyll-paginate]

highlighter: rouge
paginate: 20

markdown: rdiscount
rdiscount:
    extensions: ['smart']

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile', 'vendor']

theme: jekyll-theme-time-machine
